[package]
name = "libtrace"
version = "0.1.0"
authors = ["Nathan <nlincoln@intellifarms.com>"]
edition = "2018"

[dependencies]
rand = "0.5"
serde = { version = "1.0" }
log = "0.4"
serde_derive = "1.0"
png = "0.14"
gif = "0.10"
lazy_static = "1.3"
image = "0.21"
