[package]
name = "worker-shared"
version = "0.1.0"
authors = ["Nathan <nlincoln@intellifarms.com>"]
edition = "2018"

[dependencies]
libtrace = { path = "../libtrace" }
serde = { version = "1.0" }
serde_derive = "1.0"
